export const properties = [
  {
    id: '1',
    title: 'Modern House in the City',
    location: 'Makati, Metro Manila',
    price: 8500000,
    type: 'House',
    description:
      'A beautiful modern house with three bedrooms, two bathrooms, and a spacious garage.',
    address: '123 Ayala Ave, Makati, Metro Manila',
    amenities: ['Garage', 'Swimming Pool', 'Garden'],
    image: 'https://example.com/images/property1.jpg',
    isFavorite: true,
  },
  {
    id: '2',
    title: 'Cozy Condo with City View',
    location: 'BGC, Taguig',
    price: 4500000,
    type: 'Condo',
    description:
      'A stylish one-bedroom condo with a great city view, perfect for young professionals.',
    address: '456 High Street, BGC, Taguig',
    amenities: ['Gym', '24/7 Security', 'Swimming Pool'],
    image: 'https://example.com/images/property2.jpg',
    isFavorite: false,
  },
  {
    id: '3',
    title: 'Affordable Apartment Near MRT',
    location: 'Quezon City',
    price: 2500000,
    type: 'Apartment',
    description:
      'An affordable apartment with two bedrooms, ideal for small families.',
    address: '789 EDSA, Quezon City',
    amenities: ['Parking', '24/7 Security'],
    image: 'https://example.com/images/property3.jpg',
    isFavorite: true,
  },
  {
    id: '4',
    title: 'Modern House in the City',
    location: 'Makati, Metro Manila',
    price: 8500000,
    type: 'House 1',
    description:
      'A beautiful modern house with three bedrooms, two bathrooms, and a spacious garage.',
    address: '123 Ayala Ave, Makati, Metro Manila',
    amenities: ['Garage', 'Swimming Pool', 'Garden'],
    image: 'https://example.com/images/property1.jpg',
    isFavorite: false,
  },
  {
    id: '5',
    title: 'Cozy Condo with City View',
    location: 'BGC, Taguig',
    price: 4500000,
    type: 'Condo 1',
    description:
      'A stylish one-bedroom condo with a great city view, perfect for young professionals.',
    address: '456 High Street, BGC, Taguig',
    amenities: ['Gym', '24/7 Security', 'Swimming Pool'],
    image: 'https://example.com/images/property2.jpg',
    isFavorite: true,
  },
  {
    id: '6',
    title: 'Affordable Apartment Near MRT',
    location: 'Quezon City',
    price: 2500000,
    type: 'Apartment 1',
    description:
      'An affordable apartment with two bedrooms, ideal for small families.',
    address: '789 EDSA, Quezon City',
    amenities: ['Parking', '24/7 Security'],
    image: 'https://example.com/images/property3.jpg',
    isFavorite: false,
  },
];
