import type { tProperty } from '@/types/property';

export const properties: tProperty[] = [
  {
    id: '1',
    title: 'Modern House in the City',
    location: 'Makati, Metro Manila',
    price: 8500,
    type: 'House',
    description:
      'A beautiful modern house with three bedrooms, two bathrooms, and a spacious garage.',
    address: '123 Ayala Ave, Makati, Metro Manila',
    amenities: ['Garage', 'Swimming Pool', 'Garden'],
    image: require('@/assets/images/properties/1.jpg'),
    guestCount: 2,
    bedCount: 3,
    bathCount: 2,
  },
  {
    id: '2',
    title: 'Cozy Condo with City View',
    location: 'BGC, Taguig',
    price: 4500,
    type: 'Condo',
    description:
      'A stylish one-bedroom condo with a great city view, perfect for young professionals.',
    address: '456 High Street, BGC, Taguig',
    amenities: ['Gym', 'Security', 'Swimming Pool'],
    image: require('@/assets/images/properties/2.jpg'),
    guestCount: 4,
    bedCount: 2,
    bathCount: 1,
  },
  {
    id: '3',
    title: 'Affordable Apartment Near MRT',
    location: 'Quezon City',
    price: 2500,
    type: 'Apartment',
    description:
      'An affordable apartment with two bedrooms, ideal for small families.',
    address: '789 EDSA, Quezon City',
    amenities: ['Parking', 'Security'],
    image: require('@/assets/images/properties/3.jpg'),
    guestCount: 2,
    bedCount: 1,
    bathCount: 1,
  },
  {
    id: '4',
    title: 'Luxury Penthouse with Skyline View',
    location: 'Ortigas, Pasig',
    price: 15000,
    type: 'Condo',
    description:
      'A high-end penthouse with a 360-degree view of the Metro Manila skyline.',
    address: '88 Emerald Ave, Ortigas, Pasig',
    amenities: ['Private Elevator', 'Rooftop Pool', 'Gym'],
    image: require('@/assets/images/properties/4.jpg'),
    guestCount: 6,
    bedCount: 3,
    bathCount: 2,
  },
  {
    id: '5',
    title: 'Simple Studio in the City',
    location: 'Mandaluyong',
    price: 1800,
    type: 'Apartment',
    description:
      'A small but convenient studio near public transport and shopping centers.',
    address: '500 Boni Ave, Mandaluyong',
    amenities: ['Elevator', 'Security'],
    image: require('@/assets/images/properties/5.jpg'),
    guestCount: 2,
    bedCount: 1,
    bathCount: 1,
  },
  {
    id: '6',
    title: 'Beachfront House in Batangas',
    location: 'Nasugbu, Batangas',
    price: 12000,
    type: 'House',
    description:
      'A stunning beachfront house perfect for weekend getaways and family vacations.',
    address: 'Seaside Blvd, Nasugbu, Batangas',
    amenities: ['Beach Access', 'Swimming Pool', 'Garden'],
    image: require('@/assets/images/properties/6.jpg'),
    guestCount: 8,
    bedCount: 4,
    bathCount: 3,
  },
  {
    id: '7',
    title: 'Family Home with Spacious Backyard',
    location: 'Antipolo, Rizal',
    price: 5200,
    type: 'House',
    description:
      'A perfect family home with a wide backyard for outdoor activities.',
    address: 'Hilltop Drive, Antipolo, Rizal',
    amenities: ['Garage', 'Garden', 'Balcony'],
    image: require('@/assets/images/properties/7.jpg'),
    guestCount: 6,
    bedCount: 3,
    bathCount: 2,
  },
  {
    id: '8',
    title: 'Loft-Type Condo Near Greenbelt',
    location: 'Makati, Metro Manila',
    price: 7000,
    type: 'Condo',
    description:
      'A stylish loft-type condo unit within walking distance to Greenbelt Mall.',
    address: 'Paseo de Roxas, Makati',
    amenities: ['Gym', 'Swimming Pool', 'Sky Lounge'],
    image: require('@/assets/images/properties/8.jpg'),
    guestCount: 4,
    bedCount: 2,
    bathCount: 1,
  },
  {
    id: '9',
    title: 'Fully Furnished Condo in Cebu IT Park',
    location: 'Cebu City',
    price: 4000,
    type: 'Condo',
    description:
      'A fully furnished condo ideal for young professionals and investors.',
    address: 'Cebu IT Park, Lahug, Cebu City',
    amenities: ['Gym', 'Security', 'Swimming Pool'],
    image: require('@/assets/images/properties/9.jpg'),
    guestCount: 2,
    bedCount: 1,
    bathCount: 1,
  },
  {
    id: '10',
    title: 'Elegant House in Quezon City',
    location: 'Quezon City',
    price: 9500,
    type: 'House',
    description: 'A newly renovated elegant house perfect for large families.',
    address: 'Commonwealth Ave, Quezon City',
    amenities: ['Garage', 'Garden', 'Balcony'],
    image: require('@/assets/images/properties/10.jpg'),
    guestCount: 8,
    bedCount: 4,
    bathCount: 3,
  },
  {
    id: '11',
    title: 'Studio Condo in Davao City',
    location: 'Davao City',
    price: 2200,
    type: 'Condo',
    description:
      'Affordable studio condo in the heart of Davao City, perfect for students or starting professionals.',
    address: 'JP Laurel Ave, Davao City',
    amenities: ['Security', 'Gym', 'Swimming Pool'],
    image: require('@/assets/images/properties/1.jpg'),
    guestCount: 2,
    bedCount: 1,
    bathCount: 1,
  },
  {
    id: '12',
    title: 'Luxury Resort-Style Villa',
    location: 'Tagaytay',
    price: 18000,
    type: 'House',
    description:
      'A stunning resort-style villa with a private pool and view of Taal Lake.',
    address: 'Tagaytay-Nasugbu Hwy, Tagaytay',
    amenities: ['Private Pool', 'Garden', 'Garage'],
    image: require('@/assets/images/properties/2.jpg'),
    guestCount: 10,
    bedCount: 5,
    bathCount: 4,
  },
  {
    id: '13',
    title: 'Minimalist Condo in Alabang',
    location: 'Alabang, Muntinlupa',
    price: 3500,
    type: 'Condo',
    description:
      'A minimalist one-bedroom condo perfect for singles or couples.',
    address: 'Filinvest, Alabang, Muntinlupa',
    amenities: ['Swimming Pool', 'Gym', 'Sky Lounge'],
    image: require('@/assets/images/properties/3.jpg'),
    guestCount: 2,
    bedCount: 1,
    bathCount: 1,
  },
  {
    id: '14',
    title: 'Compact Apartment in Cubao',
    location: 'Cubao, Quezon City',
    price: 2800,
    type: 'Apartment',
    description:
      'A compact apartment near Araneta Center, ideal for working professionals.',
    address: 'P. Tuazon Blvd, Cubao, Quezon City',
    amenities: ['Security', 'Parking'],
    image: require('@/assets/images/properties/4.jpg'),
    guestCount: 3,
    bedCount: 1,
    bathCount: 1,
  },
  {
    id: '15',
    title: 'Beach Condo in Subic',
    location: 'Subic Bay',
    price: 5500,
    type: 'Condo',
    description:
      'A beachside condo unit with easy access to the shore and recreational areas.',
    address: 'Waterfront Road, Subic Bay',
    amenities: ['Swimming Pool', 'Beach Access', 'Gym'],
    image: require('@/assets/images/properties/5.jpg'),
    guestCount: 4,
    bedCount: 2,
    bathCount: 2,
  },
  {
    id: '16',
    title: 'Townhouse in Pasig',
    location: 'Pasig City',
    price: 4700,
    type: 'House',
    description: 'A cozy townhouse perfect for starter families.',
    address: 'C. Raymundo Ave, Pasig City',
    amenities: ['Garage', 'Security'],
    image: require('@/assets/images/properties/6.jpg'),
    guestCount: 5,
    bedCount: 3,
    bathCount: 2,
  },
  {
    id: '17',
    title: 'Garden Condo in Marikina',
    location: 'Marikina City',
    price: 3200,
    type: 'Condo',
    description:
      'A condo unit with direct garden access, perfect for relaxation.',
    address: 'Marcos Highway, Marikina City',
    amenities: ['Garden Access', 'Swimming Pool', 'Gym'],
    image: require('@/assets/images/properties/7.jpg'),
    guestCount: 4,
    bedCount: 2,
    bathCount: 1,
  },
  {
    id: '18',
    title: 'Mountain View House in Baguio',
    location: 'Baguio City',
    price: 6700,
    type: 'House',
    description: 'A mountain view house with a fireplace and cozy ambiance.',
    address: 'Mines View Park, Baguio City',
    amenities: ['Fireplace', 'Garage', 'Balcony'],
    image: require('@/assets/images/properties/8.jpg'),
    guestCount: 6,
    bedCount: 3,
    bathCount: 2,
  },
  {
    id: '19',
    title: 'Riverside House in Pampanga',
    location: 'San Fernando, Pampanga',
    price: 5200,
    type: 'House',
    description:
      'A lovely riverside house with wide open spaces and fresh air.',
    address: 'Riverside Drive, San Fernando, Pampanga',
    amenities: ['Garage', 'Garden', 'Balcony'],
    image: require('@/assets/images/properties/9.jpg'),
    guestCount: 6,
    bedCount: 3,
    bathCount: 2,
  },
  {
    id: '20',
    title: 'High-Rise Condo in Manila Bay',
    location: 'Manila City',
    price: 6000,
    type: 'Condo',
    description:
      'A high-rise condo with a panoramic view of Manila Bay sunset.',
    address: 'Roxas Blvd, Manila City',
    amenities: ['Swimming Pool', 'Sky Lounge', 'Gym'],
    image: require('@/assets/images/properties/10.jpg'),
    guestCount: 4,
    bedCount: 2,
    bathCount: 2,
  },
  {
    id: '21',
    title: 'Countryside Farm Lot',
    location: 'Tagaytay Highlands',
    price: 3000,
    type: 'Farm',
    description:
      'A peaceful farm lot perfect for organic farming or a weekend retreat with fresh air and mountain views.',
    address: 'Tagaytay Highlands, Cavite',
    amenities: ['Wide Lot', 'Fruit Trees', 'Water Supply'],
    image: require('@/assets/images/properties/1.jpg'),
    guestCount: 10,
    bedCount: 0,
    bathCount: 0,
  },
  {
    id: '22',
    title: 'Modern Office Space',
    location: 'Ortigas Center, Pasig',
    price: 12000,
    type: 'Office',
    description:
      'A modern office space in Ortigas with high-speed elevators, 24/7 security, and a great view of the city skyline.',
    address: 'Ortigas Center, Pasig City',
    amenities: ['High-Speed Elevator', 'Backup Generator', 'Parking'],
    image: require('@/assets/images/properties/2.jpg'),
    guestCount: 20,
    bedCount: 0,
    bathCount: 2,
  },
  {
    id: '23',
    title: 'Commercial Space in Divisoria',
    location: 'Divisoria, Manila',
    price: 8000,
    type: 'Commercial',
    description:
      'Ideal for retail businesses, this commercial space is located in the heart of Divisoria with heavy foot traffic.',
    address: 'Sto. Cristo St, Divisoria, Manila',
    amenities: ['Wide Entrance', 'Storage Area', 'Parking'],
    image: require('@/assets/images/properties/3.jpg'),
    guestCount: 15,
    bedCount: 0,
    bathCount: 1,
  },
  {
    id: '24',
    title: 'Warehouse in Valenzuela',
    location: 'Valenzuela City',
    price: 15000,
    type: 'Warehouse',
    description:
      'Spacious warehouse suitable for logistics, manufacturing, or storage with high ceiling and large truck access.',
    address: 'McArthur Highway, Valenzuela City',
    amenities: ['High Ceiling', 'Truck Bay', 'Security Gate'],
    image: require('@/assets/images/properties/4.jpg'),
    guestCount: 50,
    bedCount: 0,
    bathCount: 2,
  },
  {
    id: '25',
    title: 'Vacation Cottage by the Lake',
    location: 'Laguna',
    price: 5000,
    type: 'Cottage',
    description:
      'A charming lakeside cottage perfect for family vacations, with serene views and a relaxing atmosphere.',
    address: 'Lake Caliraya, Laguna',
    amenities: ['Lake Access', 'Private Dock', 'Garden'],
    image: require('@/assets/images/properties/5.jpg'),
    guestCount: 8,
    bedCount: 3,
    bathCount: 2,
  },
  {
    id: '26',
    title: 'Penthouse Loft in Cebu',
    location: 'Cebu IT Park',
    price: 16000,
    type: 'Loft',
    description:
      'Luxurious penthouse loft with stunning city views, rooftop access, and top-notch amenities.',
    address: 'Cebu IT Park, Lahug, Cebu City',
    amenities: ['Rooftop Deck', 'Swimming Pool', 'Gym'],
    image: require('@/assets/images/properties/6.jpg'),
    guestCount: 6,
    bedCount: 3,
    bathCount: 3,
  },
  {
    id: '27',
    title: 'Secluded Mountain Cabin',
    location: 'Sagada, Mountain Province',
    price: 2500,
    type: 'Cabin',
    description:
      'A cozy mountain cabin perfect for escaping city life and enjoying the cool Sagada breeze.',
    address: 'Echo Valley, Sagada, Mountain Province',
    amenities: ['Fireplace', 'Deck', 'Mountain Views'],
    image: require('@/assets/images/properties/7.jpg'),
    guestCount: 4,
    bedCount: 2,
    bathCount: 1,
  },
  {
    id: '28',
    title: 'Studio Office in Makati',
    location: 'Makati, Metro Manila',
    price: 3000,
    type: 'Office',
    description:
      'A compact office space perfect for startups or small businesses, located in the bustling Makati CBD.',
    address: 'Salcedo Village, Makati',
    amenities: ['Elevator Access', 'Parking', 'Security'],
    image: require('@/assets/images/properties/8.jpg'),
    guestCount: 10,
    bedCount: 0,
    bathCount: 1,
  },
  {
    id: '29',
    title: 'Retail Space in Greenhills',
    location: 'San Juan City',
    price: 9000,
    type: 'Commercial',
    description:
      'A high-visibility retail space in Greenhills Shopping Center, perfect for boutiques or cafes.',
    address: 'Greenhills Shopping Center, San Juan City',
    amenities: ['Front Display Window', 'High Foot Traffic', 'Parking'],
    image: require('@/assets/images/properties/9.jpg'),
    guestCount: 15,
    bedCount: 0,
    bathCount: 1,
  },
  {
    id: '30',
    title: 'Private Island Lot',
    location: 'Palawan',
    price: 50000,
    type: 'Island',
    description:
      'A rare opportunity to own a private island with white sand beaches and clear blue waters in Palawan.',
    address: 'Coron, Palawan',
    amenities: ['Private Beach', 'Boat Access', 'Resort Potential'],
    image: require('@/assets/images/properties/10.jpg'),
    guestCount: 20,
    bedCount: 0,
    bathCount: 0,
  },
];
