/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Light Mode
        background: '#ffffff',
        foreground: '#252525',
        card: '#ffffff',
        cardForeground: '#252525',
        popover: '#ffffff',
        popoverForeground: '#252525',
        primary: '#353535',
        primaryForeground: '#fbfbfb',
        secondary: '#f7f7f7',
        secondaryForeground: '#353535',
        muted: '#f7f7f7',
        mutedForeground: '#8e8e8e',
        accent: '#f7f7f7',
        accentForeground: '#353535',
        destructive: '#934040',
        border: '#ebebeb',
        input: '#ebebeb',
        ring: '#b5b5b5',

        chart1: '#db7c0c',
        chart2: '#3999e8',
        chart3: '#6685ff',
        chart4: '#ebba23',
        chart5: '#dcb100',

        sidebar: '#ffffff',
        sidebarForeground: '#252525',
        sidebarPrimary: '#353535',
        sidebarPrimaryForeground: '#fbfbfb',
        sidebarAccent: '#f7f7f7',
        sidebarAccentForeground: '#353535',
        sidebarBorder: '#ebebeb',
        sidebarRing: '#b5b5b5',

        // Dark Mode
        'dark-background': '#353535',
        'dark-foreground': '#fbfbfb',
        'dark-card': '#353535',
        'dark-cardForeground': '#fbfbfb',
        'dark-popover': '#353535',
        'dark-popoverForeground': '#fbfbfb',
        'dark-primary': '#ffffff',
        'dark-primaryForeground': '#353535',
        'dark-secondary': '#454545',
        'dark-secondaryForeground': '#fbfbfb',
        'dark-muted': '#454545',
        'dark-mutedForeground': '#b5b5b5',
        'dark-accent': '#454545',
        'dark-accentForeground': '#fbfbfb',
        'dark-destructive': '#b34a4a',
        'dark-border': 'rgba(255, 255, 255, 0.1)',
        'dark-input': 'rgba(255, 255, 255, 0.15)',
        'dark-ring': '#8e8e8e',

        'dark-chart1': '#6a84e0',
        'dark-chart2': '#a1da54',
        'dark-chart3': '#dcb100',
        'dark-chart4': '#6a6ad9',
        'dark-chart5': '#cc792a',

        'dark-sidebar': '#353535',
        'dark-sidebarForeground': '#fbfbfb',
        'dark-sidebarPrimary': '#6a84e0',
        'dark-sidebarPrimaryForeground': '#fbfbfb',
        'dark-sidebarAccent': '#454545',
        'dark-sidebarAccentForeground': '#fbfbfb',
        'dark-sidebarBorder': 'rgba(255, 255, 255, 0.1)',
        'dark-sidebarRing': '#8e8e8e',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};
